name: chains
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  quiver: ^3.0.1
  js: ^0.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true